platform :ios, '8.0'
target '党建' do
pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.1'
pod 'FMDB', '~> 2.7.2'
pod 'SDWebImage', '~> 5.0.0-beta2'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 6.1.1'
end
